# Generated by Django 3.2.5 on 2021-07-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('product_type', models.IntegerField(choices=[(1, 'Тип 1'), (2, 'Тип 2'), (3, 'Тип 3')], db_index=True, verbose_name='Тип')),
                ('price', models.FloatField(db_index=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
