# Generated by Django 3.2.5 on 2021-07-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продуктов'},
        ),
    ]
